### ISSUE TITLE
RSE 2021 Planning Meeting

### ISSUE THREAD

**Issue by manodeep** [rse-aunz/organisation#19]
Chair: Nooriyah
Date: 9th Feb, 2 pm AEST ([timezone converter](https://www.timeanddate.com/worldclock/converter.html?iso=20210209T030000&p1=152&p2=47&p3=196&p4=22))
Zoom info: Shared via email, will be posted here close to the meeting time

Agenda:
---------

1. Welcome back 
2. Confirm a time for a recurring meeting
3. Confirm engagement with ARDC (re. software agenda discussion)
4. eResearch NZ 2021 
5. RSE International Survey 
6. Brain-storming for RSE-related events in 2021 (e.g., C3DIS, NZ-RSE, eRA, SORSE, webinars, UK-RSE, (UK)-RSE-Leaders?) 
7. All other business

**Comment by nrmay** [comment]
Added Item 3. as per Tom Honeyman's request.
