### ISSUE TITLE
What is a Research Software Engineer?

### ISSUE THREAD

**Issue by rowlandm** [rse-aunz/organisation#2]
eg. Scripting vs building systems vs building standalone tools
How does that overlap with data scientists?

**Comment by manodeep** [comment]
Copying from the [UK RSE website](http://rse.ac.uk/)

**Are you a Research Software Engineer?**

Regardless of your formal job title, if you answer yes to many of the following questions, you are doing the work of a Research Software Engineer:

* Are you employed to develop software for research?
* Are you spending more time developing software than conducting research?
* Are you employed as a postdoctoral researcher, even though you predominantly work on software development?
* Are you the person who does computers in your research group?
* Are you sometimes not named on research papers despite playing a fundamental part in developing the software used to create them?
* Do you lack the metrics needed to progress your academic career, like papers and conference presentations, despite having made a significant contribution through software?

**Comment by manodeep** [comment]
And the results of the latest (9th March 2018), international RSE [survey](https://www.software.ac.uk/what-do-we-know-about-rses-results-our-international-surveys)

**Comment by nrmay** [comment]
Cleaning up this repo.
