### ISSUE TITLE
Steering Committee Meeting #24 (Feb 2022)

### ISSUE THREAD

**Issue by Winterstorm-j** [rse-aunz/organisation#39]
# Meeting Details:
**Chair**: TBA
**Date**:  Tues. 22nd February 2022
 
**Time**: [event timeanddate.com](https://www.timeanddate.com/worldclock/fixedtime.html?msg=Steering+Committee+Meeting+%2321&iso=20211123T14&p1=152&ah=1)

* Auckland, New Zealand: 4:00 pm (NZDT)
* Brisbane, Australia: 1:00 pm (AEST)
* Melbourne, Australia: 2:00 pm {AEDT)
* Perth, Australia: 11:00 am (AWST)

**Meeting link**: [Join Zoom Meeting](https://nesi.zoom.us/j/88635462552?pwd=QUt2S0x5ZENOSEZtRENvSUl2Y1RnQT09)

# Proposed Agenda:
### 2. Planning Activities
Quarterly online event
RSE Survey
Direction/Strategy of committee
Potential RSE Australia conference/eResearch collab
Outreachy
Metrics for RSE contributions
Impact stories

### 3. Actions From Previous Minutes:
Metrics White paper
Governance document
eResearch NZ talk

### 4. Any Other Business
* Proposed next meeting: 27/03/2022

**Comment by rowlandm** [comment]
Providing Mural link for discussion on Strategy agenda item - should not need to create an account.
https://app.mural.co/t/rsestrategy4561/m/rsestrategy4561/1645219543069/f9d287d981d299140a5900663387de88d29d0da8?sender=u14f2cac1e6bd0626fe663214
