### ISSUE TITLE
Potential RSE Asia Australia conference 2022

### ISSUE THREAD

**Issue by rowlandm** [rse-aunz/organisation#40]
My initial thoughts (sorry I missed the last meeting) would be to
 do this in September, a month before the eResearch Australasia, 
do it jointly with eResearch NZ either as separate branding or combined,
I would also like to invite Saranjeet Kaur and Batool Almarzouq to think about doing something around the same time for RSE Asia,
We would need to get help to organise this conference, just like how AeRO and NeSI helps with the eResearch and RSE NZ conferences already.

What are everyone's thoughts about these four things?

This is the key national meetings I'm aware of that are already part of the calendar.

J
F eResearchNZ
M
A
M C3DIS
J
J
A
S RSE NZ | International RSE conference| AeRO forum
O eResearchAUNZ
N
D

**Comment by rowlandm** [comment]
I did start to look at strategy.

I went through all the minutes since 2019 and tried to identify the recurring tasks of the steering commitee:

International Survey
eResearch AU events
eResearch NZ events
RSE NZ
C3DIS events
International Council RSE representation
International conference RSE events
Elections for steering committee
Partnership with ARDC
Providing feedback on behalf of the community
Looking at opportunities for the community
Sharing info with the community

That's a lot of responsibility.

It is my current opinion that the SC needs to be more strategic and needs to delegate operational things to others.

**Comment by rowlandm** [comment]
Get Linux Australia or AeRO or NeSI to organise it?

**Comment by rowlandm** [comment]
I would like to have an award for "outstanding contribution", not as a 1st 2nd 3rd but as a tier - if they achieved this, this and this they they deserve an accolade that is reviewed by a team of peers and added onto the website to help value their contribution.

**Comment by rowlandm** [comment]
Conference
3 half days RSE AU
Roll over discussion after RSE NZ
1pm to 5pm AEST

**Comment by rowlandm** [comment]
Have a keynote to start off the day, a junior RSE for the first day, a senior RSE for the second day, and a senior manager for the third day.
Make each day a half day event to be more flexible and reduce the need for filling empty gaps.
Starting in the morning of Western Australia to be more inclusive with WA and with potential Asian countries.

**Comment by rowlandm** [comment]
leadership program and mentoring ? with a socio-technical aspect.
Trainging for people moving into leadership roles as
![Screen Shot 2022-05-06 at 3 35 58 pm](https://user-images.githubusercontent.com/420050/167074020-95595ac9-658f-4769-a1de-6026305fe899.png)

**Comment by rowlandm** [comment]
training for people in the bottom row of the CMM training model and for the expert in the technical. eg. HPC Sysadmins working together.

**Comment by rowlandm** [comment]
HPC sysadmins how to improve performance - but first have a pre-unconference vote so that they can be prepared.

**Comment by rowlandm** [comment]
Helping junior devs for things like awards that are non-competitive.

**Comment by rowlandm** [comment]
have to get something out of it for volunteers to stay around.

**Comment by rowlandm** [comment]
Look at putting together or adding to user stories.

**Comment by rowlandm** [comment]
non-competitive award that is a DOI to a micro-credential.

**Comment by rowlandm** [comment]
Decide how do we vote for the polls before and during the unconference.
How do we decide and how do we get people to nominate others.

**Comment by rowlandm** [comment]
What tech for the unconference eg. Zoom etc. Need something accessible.

**Comment by rowlandm** [comment]
Refer people to other organisations like astronomers to  ADACS if they had a specific HPC question as part of one of the sessions.

**Comment by rowlandm** [comment]
Question about what if we want people to practice public speaking for their domains eg. have lightning talks?

**Comment by rowlandm** [comment]
We would need facilitators for each session that is a high topic to discuss. We may need breakoutrooms to have 3 topics in parallel, and you would need 3 facilitators.

**Comment by rowlandm** [comment]
Cross disciplinary collaboration
HPC speedup
5 Mistakes you should avoid when .....
Code review improvements.

**Comment by rowlandm** [comment]
Leadership program / mentorship.

**Comment by rowlandm** [comment]
Would we need people to give presentation jsut with a whiteboard or use slides?

**Comment by rowlandm** [comment]
pre conference vote for type of session.
Session for : 
- 5 Mistakes you should avoid when .....
- Lightning talks
- Fight club

**Comment by rowlandm** [comment]
Lightning talks for day 1 as part of junior devs
5 Mistakes could be for senior.

**Comment by rowlandm** [comment]
Could be 10 simple rules for PloS.

**Comment by rowlandm** [comment]
https://journals.plos.org/

**Comment by rowlandm** [comment]
Panel discussion as a session.

**Comment by rowlandm** [comment]
Maybe the keynote for the 3rd day is actually a panel session.

**Comment by rowlandm** [comment]
Entry low or free to help chip towards the keynotes for the first two days.

**Comment by rowlandm** [comment]
RSE Australia $10 AUD, RSE Asia could be free.

**Comment by rowlandm** [comment]
Reach out to inviduals in the RSE communities.

**Comment by rowlandm** [comment]
API design, version control, testing, code reviews, continuous integration, documentation, packaging, deployment

**Comment by rowlandm** [comment]
30th June
- Entry fee sorted for honorarium to keynote speakers.
- technology sorted
- high-level structure 3 keynotes, or 2 keynotes and a panel (recommended)
- RSE Asia and RSE Australia joint with a logo or something
- Award with DOI.
- Finalise the registration form by this time.

**Comment by SaranjeetKaur** [comment]
> 30th June
> 
> * Entry fee sorted for honorarium to keynote speakers.
> * technology sorted
> * high-level structure 3 keynotes, or 2 keynotes and a panel (recommended)
> * RSE Asia and RSE Australia joint with a logo or something
> * Award with DOI.
> * Finalise the registration form by this time.

Also finalise a call for volunteers

**Comment by SaranjeetKaur** [comment]
Article on [Ten Simple Rules for Organizing an Unconference](https://journals.plos.org/ploscompbiol/article?id=10.1371/journal.pcbi.1003905)

**Comment by rowlandm** [comment]
Example of HPC improvement of software
https://www.youtube.com/watch?v=x8tTX8N3rbQ

**Comment by rowlandm** [comment]
What if we paid the facilitators instead of the speakers?

**Comment by SaranjeetKaur** [comment]
You mean provide financial assistance to the volunteers for their work? - I
really like this thought!

Also I feel if we are able to find a few sponsors for the unconf, then it
would help resolve the payments issue (to speakers +
volunteers/facilitators).

How about writing to the society of RSE for a sponsorship?

**Comment by rowlandm** [comment]
Notes from discussion between Paula and Rowland about budget for the conference.

Please check out the spreadsheet to get a feel for the budget we were looking at.

We budgeted based on having: 
50 staff registering at $20AUD, 
50 students at $10 AUD,
having a fellowship (with a short application) that gives free entry to 25 staff ($500) and 25 students ($250) supported by ARDC,
Other comments
We assumed we could get one more sponsor at $3500 AUD to match the ARDC $3500 AUD that we are asking for in this budget,
Paula was going to share with me who the best person to reach out to sponsorships for AWS and other organisations
We thought we might have to find an organisation that could receive funds from ARDC and then provide the honorariums. 
I suggested that I have an Australian Business Number so I could potentially receive these funds and then redistribute them. For me, this is a worst-case scenario, only to be done as a last option.
We talked about how giftcards work well in Australia. 
We also talked about trying to test the conference software beforehand
We also talked about having an "all-in-one" software for registration and handling payment.
I might have missed something, but this was the main discussion

**Comment by rowlandm** [comment]
https://humanitix.com/us/pricing

https://www.eventbrite.com/organizer/pricing/

**Comment by rowlandm** [comment]
How do people pay if they don't have a credit card? eg. students?

**Comment by rowlandm** [comment]
Hi All,

I am looking for representatives for the organising committee for the joint RSE Asia Australia 2022 online unconference that is being hosted from the 14th to the 16th of September. Please also consider sending this out to colleagues or senior staff who might be able to volunteer time from an experienced event manager.

As a member of the organising committee, you will help plan and shape the event. This involves:

- attending a monthly meeting leading up to the event in September to help to identify and choose technologies and processes to help streamline the online event,
- being a champion for the event within your institution/region, and
- potentially facilitating a breakout room at the unconference.

We are currently in discussions with sponsors to provide a $100 AUD honorarium to representatives of the organising commitee. This has not been finalised yet, but the total budget for this was suggested to be $1000AUD.

Please reply to me directly via email if you are interested, or forward this onto a colleague who may be interested.

Regards,

Rowland Mosbergen
On behalf of the RSE Asia Australia 2022 organising committee

**Comment by rowlandm** [comment]
Hi All,

I met with Saranjeet Kaur (cc'ed), one of the founders of RSE Asia and we wanted to run some of the ideas we had past the steering committee as we would like a joint RSE Asia and RSE Australia conference.

What I would like to get from the steering committee via email is the OK to make this a joint conference with RSE Asia. I think this would raise the awareness of RSE Asia within the RSE AUNZ community.

Since we have not had many volunteers, I would also like to use the next two steering committee meetings (May and June) as planning events. To give you an idea of some of the things that might be discussed, I provide list that by the 30th of June we would like to have:
- the entry fee sorted to be used as an honorarium to keynote speakers (or maybe facilitators).
- the technology for voting, networking, and conferencing sorted.
- the high-level structure finalised eg. 2 keynotes for the first two days and a panel for the last day (recommended)
- some feedback on how to potentially do awards at the conference to highlight the value of RSEs.
- the registration form finalised  and
- the call for volunteers finalised.

Please feel free to answer by email as the earlier we can get feedback the quicker we can get things done as we are only 4 months away from the conference date.

**Comment by rowlandm** [comment]
What if our panel was made up of those who sponsored us?

**Comment by rowlandm** [comment]
List of potential keynotes (restricted):
https://docs.google.com/spreadsheets/d/1OjAAX8KkFPU7H3CDPnsoWKK-0nFcq1CmQNaCzE1NFCo/edit#gid=0

**Comment by SaranjeetKaur** [comment]
For the grant for volunteers:

1. Keeping the amount for the grant same, can we expand the options that individuals can have - for example, in addition to using the grant to pay for internet expenses and/or equipment like headsets/webcam/co-working space, etc., we also include the option to pay for lunch/groceries & ingredients to cook for it? I can also imagine individuals purchasing desk lighting, back cushions, etc. (This list is not exhaustive yet, but we can say some thing on the lines of "if you plan to purchase anything not included in the list then please get in touch with us for approval before purchasing".).

2. Can we rename that grant to 'accessibility and well being grant'?

**Comment by manodeep** [comment]
Reading through the ideas for the unconference - perhaps, we could set up general themes. For example, Sustainability, Equity, Efficiency, Community, etc. Then we could aim for a mix of different kinds of topics being discussed

Regarding panel members, I am somewhat against sponsors -> panel member route. If nothing else, the optics are not good on that.

**Comment by rowlandm** [comment]
https://unconference.net/unconferencing-how-to-prepare-to-attend-an-unconference-2/

**Comment by rowlandm** [comment]
https://dev.to/mattstratton/hosting-a-participant-first-conference-in-the-age-of-corona-how-to-do-it-3p2j

**Comment by rowlandm** [comment]
Draft website content

https://docs.google.com/document/d/1IencdGY2zC2PE_Llsda_wQfTbZQlNJWnUj7IUmY2VE0/edit?usp=sharing

**Comment by rowlandm** [comment]
This might be a great resource
https://www.cscce.org/resources/organizing-community-events/

For example

- [Six tips for running a successful unconference](https://www.cscce.org/2017/08/09/six-tips-for-running-a-successful-unconference/)
- [Prioritizing Accessibility in Organizing Online Events](https://www.cscce.org/2021/02/26/prioritizing-accessibility-in-organizing-online-events/)
- [The Value of #Welcome, part 2: How to prepare 40 new community members for an unconference](https://www.cscce.org/2017/08/11/the-value-of-welcome-part-2-how-to-prepare-40-new-community-members-for-an-unconference/)

Thanks to https://twitter.com/_lacion_

**Comment by SaranjeetKaur** [comment]
Meeting chat (23 May 2022):

Rowland Mosbergen11:39 AM
Setup registration to collect $
Setup home web page
Setup logo and marketing material
Organise application for scholarships
Finalise pricing for students and staff
Pradeep Rajasekhar11:41 AM
what if we give more to students?
Rowland Mosbergen11:42 AM
start with 25/25 and we can extend scholarships later on if we get sponsorship
Nicholas Tierney11:43 AM
50 scholarships available sounds good, and let the applications help dictate that
Rowland Mosbergen11:43 AM
50 scholarships where students would get a higher weighting when prioritising allocations
Nicholas Tierney11:44 AM
I think it might also depend on what some of the goals are for the money for the conference - I don't have much experience with honourariums, but for me I generally associate them with speaking at private/industry events. 

Do we know how much money it will cost?

Rowland Mosbergen11:49 AM
Request society RSE funding, Saranjeet is a member.

Rowland Mosbergen11:51 AM
R consortium and Microsoft we could ask for sponsorships. DASK as well.

Nicholas Tierney11:52 AM
Contact for Microsoft is David Smith - he might not work in the same area as he used to but could point us to the right area

Pradeep Rajasekhar11:52 AM
Contact DASK, Genevieve Buckley from Monash Uni used to work there... I can get in touch..

Rowland Mosbergen11:53 AM
Linux foundation

use the unconference fee - as a point to talk to their senior to fund them

Rowland Mosbergen12:00 PM
Ask for universities to handle the money for sponsorship. 

Ask for universities to handle the money for sponsorship. 
I'll ask WEHI or UniMelb.

Rowland Mosbergen12:02 PM
Use as a chance to talk to supervisors about valuing RSEs.

RSE student template and RSE professional template

Rowland Mosbergen12:04 PM
Templates for sponsors and students to ask

Rowland Mosbergen12:09 PM
Slack community group for a short time if not covered by conference.

Extra money could be sponsorship return

Ask during the unconference what can be done with the extra money left, if any

Rowland Mosbergen12:11 PM
Ask the community what to do with extra $

Rowland Mosbergen12:20 PM
Voting for unconference is part of registration. Plus early feel from organisers to fill out.

Rowland Mosbergen12:20 PM
Voting for unconference is part of registration. Plus early feel from organisrs to fill out.

Rowland Mosbergen12:28 PM
Send draft out to naive users.

**Comment by SaranjeetKaur** [comment]
Might be of interest for the unconference topics: 
1. Value and waste in software engineering: https://neverworkintheory.org/2022/05/23/galster-waste.html
2. How people really use GitHub Actions: https://neverworkintheory.org/2022/05/23/wessel-github-actions.html

**Comment by SaranjeetKaur** [comment]
I'll just copy this link here, as there some really interesting topics that could be explored: https://neverworkintheory.org/
check this: https://neverworkintheory.org/events/

**Comment by rowlandm** [comment]
Good for receiving money from Manodeep
https://www.trybooking.com/

**Comment by rowlandm** [comment]
Action item: Get steering committee members to ask for financial bank account or code to handle finances.

**Comment by rowlandm** [comment]
Action item: Write up financial needs.

**Comment by rowlandm** [comment]
Monash Busienss Faculty had the recognition for research software. Could ask them?

**Comment by rowlandm** [comment]
Ask MDAP again?
Curtin has a CIC?
Pawsey and NCI?

**Comment by rowlandm** [comment]
Virtually host to be able to host financials :)

**Comment by pr4deepr** [comment]
FUNDING:
In terms of Dask or their parent organisation NumFOCUS, Genevieve mentioned they usually support many open source projects and initiatives:
Sponsored Projects: https://numfocus.org/sponsored-projects

I think what we are striving for aligns with their mission: https://numfocus.org/community/mission

Genevieve suggested to contact CSIRO and ANSTO for funding. Do we know anyone there?

**Comment by rowlandm** [comment]
Action: Create a document registry for this conference.

**Comment by rowlandm** [comment]
Action: update list of sponsors to ask in spreadsheet.

**Comment by rowlandm** [comment]
Closing as this is now in a Trello board
https://trello.com/b/VGnxND7q/organisation
