### ISSUE TITLE
Results of the EOI survey

### ISSUE THREAD

**Issue by manodeep** [rse-aunz/organisation#5]
Anonymized raw data should be added into the repo itself. 

Here are the aggregate plots

--------------------

![degrees-eoi-survey-v2](https://user-images.githubusercontent.com/3004941/37326268-6531c3f0-26e5-11e8-9bf3-74da01db3453.png)

--------------------

![priorities-eoi-survey-v2](https://user-images.githubusercontent.com/3004941/37326267-64dc7ecc-26e5-11e8-947b-cc8fa8791d50.png)

--------------------

![priorities-as-function-of-degree-v2](https://user-images.githubusercontent.com/3004941/37326265-6486d274-26e5-11e8-835a-27c3225dd38f.png)

--------------------

**Comment by nrmay** [comment]
Cleaning up the repo.
