### ISSUE TITLE
Setup Eventbrite for RSEAUNZ

### ISSUE THREAD

**Issue by rowlandm** [rse-aunz/organisation#63]

**Comment by rowlandm** [comment]
username is events@rse-aunz.org  and password - please see Rowland.

**Comment by rowlandm** [comment]
Now it would be easier to get a Zoom account so we can integrated with Eventbrite. At the moment I will have to create a manual Google Meetup as I don't have a paid Zoom account. FYI @nooriyahp @manodeep

**Comment by rowlandm** [comment]
This has been done. @manodeep @nooriyahp @Winterstorm-j @orchid00 - by the way, any easier way of creating a group tag so I don't have to write down four names?

**Comment by manodeep** [comment]
@rse-aunz/steering-committee should ping all members of the RSE-AUNZ SC team.
