### ISSUE TITLE
Recruit casual to do secretarial work

### ISSUE THREAD

**Issue by rowlandm** [rse-aunz/organisation#64]

**Comment by rowlandm** [comment]
Hanna Bayer
Mon, May 8, 1:28 PM (7 days ago)
to me

Hi Rowland,

 

Just to let you know that I have an ABN now 😊:

91563238621

 

Best,

Johanna

**Comment by rowlandm** [comment]
We are still waiting on QCIF to give us a contract and then we can go ahead with this.

Details from 28th of March. We only have budget for about $2000 for the year.

The RSE AUNZ steering committee has agreed to start a trial for 3 months for a casual to fill a role which would be a combination steering committee secretary role and community outreach role. We were hoping to organise this through QCIF and wanted to ask for your help.

It would be 2 hours a month max, $60 AUD per hour and we hoped that you might know someone already at QCIF who is an RSE who might be a good fit and interested. We thought this would be easier to setup and try than other options.

Responsibilities:
Prepare agenda and ask for updates for upcoming steering committee meetings
Be a part of monthly steering committee meetings
Write up minutes from steering committee (SC) meetings to be checked by SC, then distribute to the community.
Update [github.io](http://github.io/) website when needed.

Key things to look for:
Github knowledge, or the ability to learn it quickly
Good note taking ability and ability to write formal emails and updates
Independent 
Good at tracking actions

Would you be able to help us out with this please?

**Comment by rowlandm** [comment]
Email to RSE community

---------- Forwarded message ---------
From: Rowland Mosbergen <rowland.h.mosbergen@gmail.com>
Date: Sun, Apr 16, 2023 at 8:44 AM
Subject: Paid casual position to help the RSE AUNZ steering commitee
To: Research Software Engineering in New Zealand and Australia <rse-nz-au@googlegroups.com>


Hi All,

The RSE AUNZ steering committee is offering a paid casual position for a couple of hours a month as an admin/secretary to support the steering committee for 2023.

We estimate a maximum of 4 hours per month and the rate would be $60 AUD per hour. The role would probably be paid via a casual contract or through invoicing if the successful applicant had an ABN.

The responsibilities include:

Prepare agenda and ask for updates for upcoming steering committee meetings
Be a part of monthly steering committee meetings
Write up minutes from steering committee (SC) meetings to be checked by SC, then distribute to the community.
Update [github.io](http://github.io/) website when needed.

Key skills needed:

Github knowledge, or the ability to learn it quickly
Good note taking ability and ability to write formal emails and updates
Independent
Good at tracking actions

Please email me if you are interested.

**Comment by manodeep** [comment]
@manodeep To invite Johanna to come on-board. 

Immediate tasks for her: 
- Contact Saranjeet about QCIF MoU whether they are okay with RSE-AUNZ being the sole signatory on the MoU (with the knowledge that the money is shared between the two Chapters)

**Comment by manodeep** [comment]
MoU changes:
- Unconference date change (Aug -> Sep)
- Association -> Chapter
- ~Added signatory party RSE-Asia~ (Mark has indicated that one signatory is preferred)
- ~two final invoices (RSE-AUNZ, and RSE-Asia).~ (Mark has indicated that this will be fine to do later, if necessary)

**Comment by manodeep** [comment]
- [ ] Add Johanna's GitHub username to RSE-AUNZ org and the SC team
- [ ] Add Johanna's email to the RSE-AUNZ email exploders

**Comment by rowlandm** [comment]
This has been done
