### ISSUE TITLE
QCIF Fiscal Sponsorship (ending in 2023)

### ISSUE THREAD

**Issue by rowlandm** [rse-aunz/organisation#66]

**Comment by rowlandm** [comment]
​--------- Forwarded message ---------
From: Mark Crowe <mark.crowe@qcif.edu.au>
Date: Wed, May 10, 2023 at 9:06 AM
Subject: Re: ABN
To: Rowland Mosbergen <rowland.h.mosbergen@gmail.com>


Hi Rowland, glad to hear that will work, and yes to all your questions (I’ll make sure that point 3 is covered in the agreement letter).

 

For the honorariums and Johanna’s payments, we can pay them as soon as the steering committee authorise us to do so and (in Johanna’s case) we receive an invoice. For the sponsorship, can you send me an email or whatever you sent sponsors last year, so I can formally agree to that?

 
​From: Rowland Mosbergen <[rowland.h.mosbergen@gmail.com](mailto:rowland.h.mosbergen@gmail.com)>
Date: Wednesday, 10 May 2023 at 07:37
To: Mark Crowe <[mark.crowe@qcif.edu.au](mailto:mark.crowe@qcif.edu.au)>
Cc: [steering.committee@rse-aunz.org](mailto:steering.committee@rse-aunz.org) <[steering.committee@rse-aunz.org](mailto:steering.committee@rse-aunz.org)>
Subject: Re: ABN

Hi Mark,

 

I have discussed this with the steering committee and they are in agreement for the end of October.

 

There were some things they wanted to ensure were in the contract though:

- That we can endeavour to pre-pay honorariums and other invoices before the event? This would give us enough time to handle any edge cases like we had last year.
- In a similar vein, we can pre-pay Johana's work for November if funds allow.
- In the event that we cannot find a fiscal sponsor by November, QCIF would be willing to hold the money in trust and make one final payment to close out the account when we do find a fiscal sponsor.
- I have attached a prospectus for the conference. The equivalent of $1,000 would be an Allied Partnership. Does that suffice for you?

 

Thanks again for all your help in this Mark - it is greatly appreciated!

**Comment by rowlandm** [comment]
Mark Crowe
May 9, 2023, 11:09 AM (6 days ago)
to me

Hi Rowland, I have had a reply from Sach. We can continue to provide financial management support up to the end of October as discussed, but with a change in how we account for it. What we’d want to do is to charge RSE Australia (or RSE Asia/Australia, depending on who is the unconference host) $1000 to provide that service, but we would also sponsor the unconference for $1000, so like last year it would come at effectively no cost to you. Are you comfortable with that option? If so, I’ll get a letter of agreement drafted and we can get things finalised.

 

Actually, now I think about it, do you already have a sponsors letter or similar for the unconference? That would save me having to write something up in our letter, and would (on paper) keep the two transactions separate.

**Comment by rowlandm** [comment]
---------- Forwarded message ---------
From: Rowland Mosbergen <rowland.h.mosbergen@gmail.com>
Date: Tue, May 23, 2023 at 10:57 AM
Subject: Re: ABN
To: Mark Crowe <mark.crowe@qcif.edu.au>
Cc: steering.committee@rse-aunz.org <steering.committee@rse-aunz.org>


Hi Mark,

Thanks for the MoU, could we please have some time to discuss with RSE Asia as they are our partners in the unconference. One of the questions we would be asking them is if they would need to be a signatory to this MoU. Is this an option from QCIF's point of view?

We probably need two invoices at the end of the contract, one for RSE Asia and one for RSE-AUNZ, and there are a few minor changes we want to confirm before getting back to you.

Please reply all to this email to keep the RSE-AUNZ steering committee in the loop.

**Comment by rowlandm** [comment]
Johanna to follow this up as part of her role  as per https://github.com/rse-aunz/organisation/issues/64#issuecomment-1558282261

**Comment by rowlandm** [comment]
On Tue, May 23, 2023 at 4:59 PM Rowland Mosbergen <rowland.h.mosbergen@gmail.com> wrote:
Thanks Mark - that has been noted and we will get back to you as soon as possible.

Yes, that is right, one for RSE Asia and one for RSE-AUNZ. 

Regards,


Rowland Mosbergen 
Strategic Leadership | Change Management | Diversity & Inclusion
B of Eng (Aerospace Avionics)
Mob: 0423 030 626
Email: [rowlandm@practicaldiversity.org](mailto:rowlandm@practicaldiversity.org)
Web: https://www.practicaldiversity.org/


On Tue, May 23, 2023 at 11:24 AM Mark Crowe <[mark.crowe@qcif.edu.au](mailto:mark.crowe@qcif.edu.au)> wrote:
Hi Rowland, I would prefer if we can keep it to one signatory if you can manage that please – ideally whoever is the chair of the unconference organising committee (which I presume is you?). As far as I and QCIF are concerned, that person would represent all the organisers.

 

When you say two invoices at the end, you mean that you’d send us two disbursement invoices for payment – one each from RSE Asia and RSE Australia? I can change that wording if we do need to make edits to the proposal, but otherwise I’m happy to confirm here in writing that we would do that as a contract variation with no resulting fees or requirements.

 

Cheers


Mark

**Comment by manodeep** [comment]
## Fiscal Sponsorship

Updates
- Reach out to RSE Asia to see if they would want to have a MoU with RSE-AUNZ or trust us with managing and sharing the money
- Mark has indicated they would prefer to have a single signatory (Rowland) to the MoU. They can also accommodate two final invoices (instead of one) to transfer money to fiscal sponsors of RSE-AUNZ and RSE-Asia

- Change “RSE AUNZ intends to establish itself as a legal entity by the end of 2023, and QCIF’s support is intended to assist it up to that point only.” To “QCIF’s support is intended to assist RSE-AUNZ up to the time that they can find another fiscal sponsor.

**Comment by manodeep** [comment]
Linking to the comments for the MoU wording changes noted under a different item: https://github.com/rse-aunz/organisation/issues/64#issuecomment-1558283418

**Comment by rowlandm** [comment]
This was finalised with QCIF and signed by Rowland. Document added to Google drive under documentation folder.
